kind: pipeline
type: docker
name: node

steps:
  - name: noderun
    image: node
    commands:
      - npm install
      - npm ci
      - npm test
      - npx codecov -t :secret:f15YREnR7axRnVWwKmymWHRFiSx51msYuSDfsGsyfjB3ucCNeJu2tqYut+kjX3mklu51VbVQzvOF2Jm4QPVyxU8sVMk4yUwdexkSgDIV9+o=
