kind: pipeline
type: docker
name: node

steps:
  - name: noderun
    image: node
    commands:
      - npm ci
      - npm test
      - CODECOV_TOKEN="0fc721ee-7baa-4492-b2b6-c23002e54627" && npx codecov --disable=gcov
