kind: pipeline
type: docker
name: node

steps:
  - name: noderun
    image: node
    commands:
      - npm ci
      - npm test
      - npx codecov -t "0fc721ee-7baa-4492-b2b6-c23002e54627" --disable=gcov
